[package]
name = "dpbriggs-blog"
version = "0.2.0"
authors = ["David Briggs <dpbriggs@edu.uwaterloo.ca>"]
edition = "2018"

[dependencies]
rocket = "0.4"
lazy_static = "1.2.0"
select = "0.4.2"
serde = "1.0.87"
serde_derive = "1.0.87"
chrono = { version = "0.4.6", features = ["serde"] }
simple_logger = "1.0.1"
log = "0.4.6"

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["tera_templates", "serve"]
